
#RGB_MATRIX_ENABLE = no
#RGBLIGHT_ENABLE = yes
OLED_ENABLE = yes
LTO_ENABLE = yes
WPM_ENABLE = yes
COMBO_ENABLE = yes

ENCODER_ENABLE = no
CONVERT_TO = liatris
MOUSEKEY_ENABLE = yes
AUTO_SHIFT_ENABLE = yes

# test RGB
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes

